name: ui_maker
description: A flutter package for user UI-creation using draggable widgets and the isar database solution.
version: 1.0.0+1
homepage: https://github.com/xanmankey/UI-Maker

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.0.5
  flutter_colorpicker: ^1.0.3
  build_runner: ^2.3.3
  isar_flutter_libs: ^3.0.5
  isar_generator: ^3.0.5
  file_picker: ^5.2.1
  contextmenu: ^3.0.0

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.22.0

flutter:
  uses-material-design: true